SELECT * FROM FAM_REQ_HEADER;
SELECT * FROM  FAM_REQ_DETAIL;
SELECT * FROM CUSR.CU_FACTORY_M;
SELECT * FROM FAM_CODE_MASTER;
SELECT * FROM FAM_FLOW_MASTER;
SELECT
  T.FAM_FACTORY,
  CU.FACTORY_CODE,
  T.FAM_REQ_TYPE,
  T.FAM_REQ_STATUS
FROM
  FAM_REQ_HEADER T
  LEFT JOIN CUSR.CU_FACTORY_M CU ON CU.FACTORY_CODE = T.FAM_FACTORY 
WHERE
  T.FAM_FACTORY = '5';
 
 SELECT T.FRH_FAM_NO , C.FRD_ASSET_NAME FROM FAM_REQ_HEADER T LEFT JOIN FAM_REQ_DETAIL C ON C.FRD_FAM_NO = T.FRH_FAM_NO WHERE T.FRH_FAM_NO ='A1-R438-23-0001'
 
-- SELECT T.FAM_REQ_TYPE  FROM FAM_REQ_HEADER T INNER JOIN FAM_CODE_MASTER R ON  R.FCM_CODE = T.FAM_REQ_TYPE  WHERE R.FCM_GROUP_ID = 'GP01' 
-- SELECT T.FAM_REQ_STATUS FROM FAM_REQ_HEADER T INNER JOIN FAM_FLOW_MASTER F ON F.FFM_CODE = T.FAM_REQ_STATUS WHERE F.FFM_TYPE = 'TRANSFER'
-- SELECT M.FACTORY_NAME FROM CUSR.CU_FACTORY_M M INNER JOIN FAM_REQ_HEADER T ON T.FAM_FACTORY  = M.FACTORY_CODE WHERE M.FACTORY_CODE ='2000'
 
 
-- //ผลลัพทธ์ทุกตัว ที่เรียกมา
-- SELECT M.FACTORY_NAME,T.FAM_REQ_CC ,T.FRH_FAM_NO ,T.FAM_REQ_DATE,T.FAM_REQ_BY ,R.FCM_DESC,C.FRD_ASSET_CODE , F.FFM_DESC 
--   FROM FAM_REQ_HEADER T INNER JOIN  CUSR.CU_FACTORY_M M ON M.FACTORY_CODE =T.FAM_FACTORY 
-- INNER JOIN FAM_CODE_MASTER R ON  R.FCM_CODE = T.FAM_REQ_TYPE 
-- INNER JOIN FAM_FLOW_MASTER F ON F.FFM_CODE = T.FAM_REQ_STATUS 
-- INNER JOIN FAM_REQ_DETAIL C ON C.FRD_FAM_NO = T.FRH_FAM_NO 
-- WHERE T.FAM_FACTORY ='2000' AND R.FCM_GROUP_ID = 'GP01' AND  F.FFM_TYPE = 'TRANSFER'
-- AND C.FRD_FAM_NO ='A1-R438-23-0001'
--  
 
 
-- ค้นหา fixed asset code 
-- SELECT  C.FRD_ASSET_CODE , C.FRD_ASSET_NAME ,C.FRD_COMP 
-- ,C.FRD_OWNER_CC ,C.FRD_ASSET_NAME 
-- ,C.FRD_BOI_PROJ ,C.FRD_QTY 
-- ,C.FRD_INV_NO ,C.FRD_ACQ_COST 
-- ,C.FRD_BOOK_VALUE 
-- FROM FAM_REQ_HEADER T 
-- INNER JOIN  CUSR.CU_FACTORY_M M ON M.FACTORY_CODE =T.FAM_FACTORY 
-- INNER JOIN FAM_CODE_MASTER R ON  R.FCM_CODE = T.FAM_REQ_TYPE 
-- INNER JOIN FAM_FLOW_MASTER F ON F.FFM_CODE = T.FAM_REQ_STATUS 
--  LEFT JOIN FAM_REQ_DETAIL C ON C.FRD_FAM_NO = T.FRH_FAM_NO 
-- WHERE T.FRH_FAM_NO ='A1-R438-23-0001'
-- 

 